const EErrors = {
    ROUTING_ERROR: 1,
    INVALID_TYPES_ERROR: 2,
    DATABASE_ERROR: 3,
    PASSWORDS_DONT_MATCH: 4,
    INVALID_CREDENTIALS: 5,
    NOT_FOUND: 6,
    DUPLICATED_CODE: 7
}

export default EErrors